###
POST http://localhost:3000/api/dangnhap/TaoTaiKhoan
Content-Type: application/json

{
    "HoTen": "Phong",
    "TaiKhoan": "test4" ,
    "MatKhau": "123"
}
###
GET http://localhost:3000/api/admin/check/connect_mysql
Content-Type: application/json
Authorization: 2
###
POST http://localhost:3000/api/admin/dangnhap/Login?taikhoan=admin&&matkhau=123
Content-Type: application/json
###
GET http://localhost:3000/api/admin/dangnhap/Logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZjFkNGZiMjctZmFhZC00MGNmLWJkYjMtNjNhMGViMTBkMDM0IiwiaWQiOjgwLCJUaG9uZ1RpbkNhTmhhbiI6eyJpZCI6ODAsIkhvVGVuIjoiUGhvbmcgxJHhurlwIHRyYWkiLCJOZ2F5U2luaCI6bnVsbCwiR2lvaVRpbmgiOm51bGwsIkVtYWlsIjpudWxsLCJEaWFDaGkiOm51bGwsIkFuaERhaURpZW4iOm51bGwsIlNEVCI6bnVsbH0sIlF1eWVuIjpbeyJUZW5EdUFuIjoiQWNjb3VudCIsInJvbGVzIjpbXX1dLCJpYXQiOjE2MzYyNTMzOTEsImV4cCI6MTYzNjI1Njk5MX0.wcl10iLBJaciQ40t-TwXKzLSgPrj8LbQlrIbRqsgA04
###
GET http://localhost:3000/api/admin/dangnhap/RefreshToken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYmVlZmM4MTgtYWY1Zi00Y2M0LWE5MmItOTBkODg1Y2I5ZDAwIiwiaWQiOjEsIlRob25nVGluQ2FOaGFuIjp7ImlkIjoxLCJIb1RlbiI6IlBob25nIiwiTmdheVNpbmgiOm51bGwsIkdpb2lUaW5oIjpudWxsLCJFbWFpbCI6bnVsbCwiRGlhQ2hpIjpudWxsLCJBbmhEYWlEaWVuIjpudWxsLCJTRFQiOm51bGx9LCJRdXllbiI6W3siQWRtaW4iOlsiVGVzdCIsIlPhu61hIHF1eeG7gW4iLCJUaMOqbSBxdXnhu4FuIiwiU-G7rWEgdMOgaSBraG_huqNuIiwiVOG6oW8gdMOgaSBraG_huqNuIl19LHsiUHVibGlzaCI6WyJWw6kgc-G7kSJdfV0sImlhdCI6MTY0MTEwNDU1MiwiZXhwIjoxNjQxMTA4MTUyfQ.jTjo0wI1PsQ5JaPi3bEqE6yY5Q8Ezw8_RkRxN7dlSJU
###
GET http://localhost:3000/api/admin/menu/AllMenu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiOThlYmMwZGYtODhjYy00NGE0LWFhZjctNjRkMjgwZGM3YjAxIiwiaWQiOjEsIlRob25nVGluQ2FOaGFuIjp7ImlkIjoxLCJIb1RlbiI6IlBob25nIiwiTmdheVNpbmgiOm51bGwsIkdpb2lUaW5oIjpudWxsLCJFbWFpbCI6bnVsbCwiRGlhQ2hpIjpudWxsLCJBbmhEYWlEaWVuIjpudWxsLCJTRFQiOm51bGx9LCJRdXllbiI6W3siQWRtaW4iOlsiVOG6oW8gdMOgaSBraG_huqNuIiwiU-G7rWEgdMOgaSBraG_huqNuIiwiVGjDqm0gcXV54buBbiIsIlPhu61hIHF1eeG7gW4iLCJUZXN0Il19LHsiUHVibGlzaCI6WyJWw6kgc-G7kSJdfSx7Ik5ndXlldEh5IjpbIk1lbnUiXX1dLCJpYXQiOjE2NDExMDc4MTYsImV4cCI6MTY0MTExMTQxNn0.4OzYINZrvakAcsN-iqhuNE89V9e7ZqBxEBelP5LhIYI
###
GET http://localhost:3000/api/phanquyen/DSNhomQuyen?isInfor=true&&isFilter=true
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNmI2YjM1MzctNzJkMi00Y2FlLTgxZjYtMmEzN2IxYzgzMzQwIiwiaWQiOjEsIlRob25nVGluQ2FOaGFuIjp7ImlkIjoxLCJIb1RlbiI6IlBob25nIiwiTmdheVNpbmgiOm51bGwsIkdpb2lUaW5oIjpudWxsLCJFbWFpbCI6bnVsbCwiRGlhQ2hpIjpudWxsLCJBbmhEYWlEaWVuIjpudWxsLCJTRFQiOm51bGx9LCJRdXllbiI6W3siUHVibGlzaCI6WyJUZXN0IiwiVsOpIHPhu5EiXX0seyJOZ3V5ZXRIeSI6WyJRdeG6o24gbMO9IG5ow6JuIHZpw6puIiwiVGjDqm0gbmjDom4gdmnDqm4iLCJDaOG7iW5oIHPhu61hIE1lbnUiLCJYb8OhIG5ow6JuIHZpw6puIl19LHsiQWNjb3VudCI6WyJUaMOqbSBuZ8aw4budaSBkw7luZyJdfV0sImlhdCI6MTYzOTY0OTkyMCwiZXhwIjoxNjM5NjUzNTIwfQ.pkvW8WlznVwNUr9ApWX5b-BIF0CGJ58_6xt2omHuf5c
###
POST http://localhost:3000/api/phanquyen/QuanLyDuAn
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNmI2YjM1MzctNzJkMi00Y2FlLTgxZjYtMmEzN2IxYzgzMzQwIiwiaWQiOjEsIlRob25nVGluQ2FOaGFuIjp7ImlkIjoxLCJIb1RlbiI6IlBob25nIiwiTmdheVNpbmgiOm51bGwsIkdpb2lUaW5oIjpudWxsLCJFbWFpbCI6bnVsbCwiRGlhQ2hpIjpudWxsLCJBbmhEYWlEaWVuIjpudWxsLCJTRFQiOm51bGx9LCJRdXllbiI6W3siUHVibGlzaCI6WyJUZXN0IiwiVsOpIHPhu5EiXX0seyJOZ3V5ZXRIeSI6WyJRdeG6o24gbMO9IG5ow6JuIHZpw6puIiwiVGjDqm0gbmjDom4gdmnDqm4iLCJDaOG7iW5oIHPhu61hIE1lbnUiLCJYb8OhIG5ow6JuIHZpw6puIl19LHsiQWNjb3VudCI6WyJUaMOqbSBuZ8aw4budaSBkw7luZyJdfV0sImlhdCI6MTYzOTY0OTkyMCwiZXhwIjoxNjM5NjUzNTIwfQ.pkvW8WlznVwNUr9ApWX5b-BIF0CGJ58_6xt2omHuf5c

{
    "Loai": "XoaDuAn",
    "IdDuAn": 55
}
###
POST http://localhost:3000/api/test/test/testpost
Content-Type: application/json

{
    "abc": "XoaDuAn",
    "d": 55
}
###
GET http://localhost:3000/api/admin/check/env
